### PR TITLE
add a {team,cluster,application}-metrics.json

### PR DESCRIPTION
**Pull request by dneuhaeuser-zalando**
This adds a file with team-level metrics to at least partially address #32.

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks for the PR!

**Comment by hjacobs** [comment]
I wonder if it would not be easier to have separate metrics files like `team-metrics.json`, `cluster-metrics.json` and `application-metrics.json` which makes it easier to scrape by the needed dimension. Having one file per team with all contents would need scraping each file (where does the monitoring software get the team list from?).

**Comment by dneuhaeuser-zalando** [comment]
I was just almost finished writing a comment about how as a Zalando
developer the approach as-is, works out perfectly well because zmon has
type:team entities and then I realized that we don’t have something that
corresponds to applications (across infrastructures).

So in the interest of consistency it definitely makes more sense to just
have one file per dimension as you suggest. At least for me :)

I’ll look into changing the PR tomorrow or so.

> --
Daniel Neuhäuser
Software Engineer
Pricing Commercial Interface (Sonic)

**Comment by hjacobs** [comment]
@dneuhaeuser-zalando actually (unrelated to this PR) we have global application entities (Kio applications) in Zalando's internal ZMON.

**Comment by hjacobs** [comment]
I'm fine with the proposal for now, but cleaning it up a bit makes sense (as the JSON is kind of an API and we should not expose too much internals which cannot be relied on, e.g. the metrics should not pass through raw Kubernetes objects I think)

**Pull request merged**
