### PR TITLE
GCP N2(D) instance types

### LINKED ISSUE #116: Cannot get prices for N2 GCP instances
The `pricing.py` pulls data from https://cloudpricingcalculator.appspot.com/static/data/pricelist.json?v=1563953523378, and this includes pricing for the newer N2 instances. However, the related entries don't match the `CP-COMPUTEENGINE-VMIMAGE-` prefix, so these prices are left out.

### PR DESCRIPTION
**Pull request by mgoodness**
Closes #116 

My Python is not strong, so please be gentle.

### CODE REVIEW

**Comment by mgoodness** [comment]
Still working on logic for custom instances.

**Comment by hjacobs** [comment]
Thanks! Does it work for you (on GCP) with this format / instance types?

**Comment by mgoodness** [comment]
Yes, though I've only actively tested against predefined, non-preemptible n2d instances. The calculated monthly cost is generally within $1US of GCP's "official" numbers.

I'm trusting my math that the other (custom, preemptible) classes are similarly accurate.

**Comment by mgoodness** [comment]
It seems there a number of other instance types that follow this pattern. Will see if I can handle them more elegantly. Converting back to a draft.

**Comment by mgoodness** [comment]
This now handles a wider variety of nextgen GCP instance types, and I've tested a number of them satisfactorily.

**Pull request merged**
