### PR TITLE
fix for gcp

### LINKED ISSUE #152: current gcp data does not work with parser

### PR DESCRIPTION
**Pull request by yashbhutwala**
- [x] fix gcp data (fix #152)
- [x] fix gcp pricing parsing
- [x] add pricing switches in helm chart
- [x] set default pricing to gcp in process
- [x] set default pricing to gcp in deploy/
- [x] fix rbac in helm chart
- [x] add rbac in deploy/

### CODE REVIEW

**Comment by yashbhutwala** [comment]
@hjacobs fixed the CI issue, this change is needed for this to work with gcp data.  When you get a chance, can you please take a look?  open to other approach to fix the data 😄

**Comment by hjacobs** [comment]
Why do you manually pass the GCP pricing CSV? What did not work with GCP?

**Comment by yashbhutwala** [comment]
@hjacobs does it autodetect that it's gcp and use that csv accordingly?  I thought I had to pass it in, maybe I misunderstood something.

**Comment by hjacobs** [comment]
@yashbhutwala did you try deploying it on GKE without any modifications? It should use the built-in CSV file automatically.

**Comment by yashbhutwala** [comment]
@hjacobs actually it does use it correctly without modifications, which is awesome!!  However if I wanted to use a latest generated csv, I would need this change, correct?

**Comment by hjacobs** [comment]
I will re-generate the files and open a new PR.

**Comment by hjacobs** [comment]
@yashbhutwala see #156

**Comment by yashbhutwala** [comment]
Sounds good

**Comment by yashbhutwala** [comment]
@hjacobs made #158 from the yaml fixes in this PR, in case you still want those 🙃

**Pull request closed without merging**
